### ISSUE TITLE
Startup errors of LMS get obscured by squeezeboxserver_safe script

### ISSUE THREAD

**Issue by stsichler** [LMS-Community/slimserver-platforms#6] opened 2018-02-05 17:54 UTC
The squeezeboxserver_safe script starts up the actual server with ">/dev/null 2>&1" redirects. 
I understand that this may be meaningful under normal conditions, because otherwise log output of the actual server would be logged twice.
On the other hand, when LMS cannot start (let's say because of Perl module dependency errors - as I recently had), no error will be logged at all!
I see several such error reports in forums on the net saying "Logitechmedia server died. Restarting." and there is no clue what actually happened, because the log file is empty.

How to solve that issue?

**Comment by michaelherger** [comment] 2018-02-12 14:31
Agreed. This should be handled in a better way. Unfortunately I wouldn't know how.

OTOH that message almost always is caused by missing Perl modules...

**Comment by stsichler** [comment] 2018-02-12 14:42
One solution may be to not redirect to /dev/null, but instead to a separate squeezeboxserver_safe.log (along with the other log output of the script) and to disable logging to console for LMS itself.
Maybe some "-nostdoutlog" option for example?

**Comment by mw9** [comment] 2018-02-21 15:12
You can end up with an enormous, spammed, `squeezeboxserver_safe.log `. Not good on an unattended system. I know this ! 😬 

I came up with half a solution a while ago, but moved on. Will try to dig it out.

**Comment by mherger** [comment] 2021-02-18 05:38
I believe @mw9 fixed this a few days ago in 8.2 by adding systemd support?

See https://github.com/Logitech/slimserver-platforms/commit/14334b3edeae198424f6d48109fb810b1cd13959

**Comment by mw9** [comment] 2021-02-18 16:02
Yes, fixed on a `systemd` system, which no longer uses `squeezeboxserver_safe`. That probably covers the substantial majority of Debian package users.

Users who will continue to "suffer" from `squeezeboxserver_safe` are those who run systemd-free systems - example Devuan - and users of ancient Debian based systems.

Personally I would not be inclined to pursue this particular issue any further, unless a material demand arises. Whatever its faults, the `squeezeboxserver_safe` script is known to work.

**Comment by stsichler** [comment] 2021-02-18 16:07
> Yes, fixed on a `systemd` system, which no longer uses `squeezeboxserver_safe`.

What about deliberate LMS restarts by the Web Interface, let's say when some Plugin needed an update? Is this still possible now? I have in mind that this restart was previously handled by `squeezeboxserver_safe`.
I haven't tested this, though.

**Comment by mw9** [comment] 2021-02-18 16:12
> What about deliberate LMS restarts by the Web Interface, let's say when some Plugin needed an update? Is this still possible now? I have in mind that this restart was previously handled by `squeezeboxserver_safe`.
> I haven't tested this, though.

On Debian, LMS restarts itself by way of an `exec` call, which doesn't terminate the process.
Unless, of course, I'm wrong... feel free to test !

**Comment by mherger** [comment] 2021-03-01 05:36
Thanks!

**Closed as completed by mherger** 2021-03-01 05:36 UTC
Labels: enhancement
